name: dwd-ingest
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_SUPER_USER}
      POSTGRES_PASSWORD: ${PG_SUPER_PASS}
      PG_DB: ${PG_DB}
      PG_WRITER_USER: ${PG_WRITER_USER}
      PG_WRITER_PASS: ${PG_WRITER_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./postgres_init:/docker-entrypoint-initdb.d:ro

  ingest:
    build: ./ingest
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=${PG_DB}
      - PG_USER=${PG_WRITER_USER}
      - PG_PASS=${PG_WRITER_PASS}
    depends_on:
      - postgres

volumes:
  pg_data:
  grafana_data:
