name: dwd-ingest
services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_SUPER_USER}
      - POSTGRES_PASSWORD=${PG_SUPER_PASS}
      - PG_DB=${PG_DB}
      - PG_WRITER_USER=${PG_WRITER_USER}
      - PG_WRITER_PASS=${PG_WRITER_PASS}
      - PG_GRAFANA_USER=${PG_GRAFANA_USER}
      - PG_GRAFANA_PASS=${PG_GRAFANA_PASS}
      - PG_NAGIOS_USER=${PG_NAGIOS_USER}
      - PG_NAGIOS_PASS=${PG_NAGIOS_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./postgres_init:/docker-entrypoint-initdb.d:ro

  grafana:
    image: grafana/grafana:9.5.0
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASS}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=${PG_DB}
      - PG_USER=${PG_GRAFANA_USER}
      - PG_PASS=${PG_GRAFANA_PASS}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres

  nagios:
    build:
      context: ./nagios
      args:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_NAGIOS_USER=${PG_NAGIOS_USER}
    environment:
      - PGPASSWORD=${PG_NAGIOS_PASS}
    ports:
      - "8080:80"
    volumes:
      - ./nagios/etc/monitor/postgres.cfg:/opt/nagios/etc/monitor/postgres.cfg
      - ./nagios/var:/opt/nagios/var
    depends_on:
      - postgres

  ingest:
    build: ./ingest
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=${PG_DB}
      - PG_USER=${PG_WRITER_USER}
      - PG_PASS=${PG_WRITER_PASS}
    depends_on:
      - postgres

volumes:
  pg_data:
  grafana_data:
