{
 "title": "Temperatures",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "station_id",
    "label": "Station",
    "query": "SELECT id AS __value, name AS __text FROM station ORDER by name;"
   }
  ]
 },
 "panels": [
  {
   "title": "Station temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, temperature_2m_c\r\nFROM temperature\r\nWHERE station_id = $station_id\r\nORDER BY timestamp DESC;\r\n"
    }
   ]
  },
  {
   "title": "Maximum measured temperature",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.name AS \"Station name\",\r\n  t.temperature_2m_c AS \"Temperature (°C)\",\r\n  (t.timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'Europe/Berlin') AS \"Date, time\"\r\nFROM temperature AS t\r\nINNER JOIN station AS s ON t.station_id = s.id\r\nWHERE t.temperature_2m_c = (\r\n  SELECT MAX(temperature_2m_c) FROM temperature\r\n);"
    }
   ]
  },
  {
   "title": "Minimum measured temperature",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.name AS \"Station name\",\r\n  t.temperature_2m_c AS \"Temperature (°C)\",\r\n  (t.timestamp AT TIME ZONE 'UTC' AT TIME ZONE 'Europe/Berlin') AS \"Date, time\"\r\nFROM temperature AS t\r\nINNER JOIN station AS s ON t.station_id = s.id\r\nWHERE t.temperature_2m_c = (\r\n  SELECT MIN(temperature_2m_c) FROM temperature WHERE temperature_2m_c > -999\r\n);"
    }
   ]
  }
 ]
}